// Prebuild step. Two jobs, both keep a single source of truth:
//   1. Embed ../esquema/schema.sql (the canonical schema, Fase 2) as a JS module so the
//      worker can apply it without a runtime fetch (no base-path / SW surprises).
//   2. Copy sqlite3.wasm into static/ so it is served at `${base}/sqlite/sqlite3.wasm`,
//      letting us override the wasm `locateFile` with a base-aware URL.
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const appDir = resolve(here, '..');
const repoDir = resolve(appDir, '..');

// 1. schema.sql -> src/lib/db/schema-sql.js
const schemaPath = resolve(repoDir, 'esquema', 'schema.sql');
const schemaSql = readFileSync(schemaPath, 'utf8');
const genDir = join(appDir, 'src', 'lib', 'db');
mkdirSync(genDir, { recursive: true });
const banner =
  '// AUTO-GENERATED by scripts/prepare-assets.mjs from ../esquema/schema.sql — do not edit by hand.\n';
writeFileSync(
  join(genDir, 'schema-sql.js'),
  banner + 'export const SCHEMA_SQL = ' + JSON.stringify(schemaSql) + ';\n'
);

// 2. sqlite3.wasm -> static/sqlite/sqlite3.wasm
const wasmSrc = resolve(
  appDir,
  'node_modules',
  '@sqlite.org',
  'sqlite-wasm',
  'dist',
  'sqlite3.wasm'
);
const wasmDestDir = join(appDir, 'static', 'sqlite');
mkdirSync(wasmDestDir, { recursive: true });
copyFileSync(wasmSrc, join(wasmDestDir, 'sqlite3.wasm'));

console.log('[prepare-assets] schema-sql.js generated; sqlite3.wasm copied to static/sqlite/.');
