// Prebuild step (Stage 3 / Supabase): bake the PUBLIC Supabase config into a JS module so the
// client can read it without a runtime fetch. ONLY the publishable values (URL + publishable
// key) — NEVER the secret. Read from process.env (CI: GitHub Actions vars) falling back to the
// repo-root .env (local dev, gitignored).
//
// (The old SQLite-WASM embed of schema.sql and the wasm copy were removed with the local
//  durability layer — Postgres is the source of truth now.)
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const appDir = resolve(here, '..');
const repoDir = resolve(appDir, '..');
const genDir = join(appDir, 'src', 'lib', 'db');
mkdirSync(genDir, { recursive: true });

function readPublicEnv(key) {
  if (process.env[key]) return process.env[key];
  try {
    const raw = readFileSync(resolve(repoDir, '.env'), 'utf8');
    for (const line of raw.split(/\r?\n/)) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
      if (m && m[1] === key) {
        let v = m[2];
        if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) v = v.slice(1, -1);
        return v;
      }
    }
  } catch {
    /* no .env */
  }
  return '';
}

const supaUrl = readPublicEnv('PUBLIC_SUPABASE_URL') || readPublicEnv('SUPABASE_URL');
const supaPublishable = readPublicEnv('PUBLIC_SUPABASE_PUBLISHABLE_KEY') || readPublicEnv('SUPABASE_PUBLISHABLE_KEY');
if (/sb_secret_/.test(supaPublishable)) {
  throw new Error('[prepare-assets] ¡La publishable parece una SECRET! Abortando para no filtrarla al bundle.');
}
writeFileSync(
  join(genDir, 'supabase-config.js'),
  '// AUTO-GENERATED by scripts/prepare-assets.mjs — PUBLIC values only (never the secret).\n' +
    `export const SUPABASE_URL = ${JSON.stringify(supaUrl)};\n` +
    `export const SUPABASE_PUBLISHABLE_KEY = ${JSON.stringify(supaPublishable)};\n`
);

if (!supaUrl || !supaPublishable) {
  console.warn('[prepare-assets] AVISO: PUBLIC_SUPABASE_URL / PUBLIC_SUPABASE_PUBLISHABLE_KEY vacías (¿falta .env o vars de CI?).');
} else {
  console.log('[prepare-assets] supabase-config.js generado (PUBLIC_*).');
}
